apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: equipe-6
  source:
    repoURL: "https://github.com/yapcyber/Hackathon_OVH_Equipe_6.git"
    targetRevision: main
    path: infra/argocd/applications
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
